---
title: "R Data basic"
author: "R 기초"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1 데이터 파악

# 범주형 데이터 생성하기
ex_vector5 <- c(2, 1, 3, 2, 1)
ex_vector5

cate_vector5 <- factor(ex_vector5, labels = c("Apple", "Banana", "Cherry"))
cate_vector5


# 행렬 데이터 생성하기
x <- c(1, 2, 3, 4, 5, 6)
matrix(x, nrow = 2, ncol = 3)
matrix(x, nrow = 3, ncol = 2)


# 옵션 추가로 결과 비교하기
x <- c(1, 2, 3, 4, 5, 6)
matrix(x, nrow = 2, ncol = 3)
matrix(x, nrow = 2, ncol = 3, byrow = T)


# 배열 생성하기
y <- c(1, 2, 3, 4, 5, 6)
array(y, dim = c(2, 2, 3))


# 리스트 생성하기
list1 <- list(c(1, 2, 3), "Hello")
list1


# 변수 속성 확인하기
str(list1)


# 데이터 프레임 생성하기
ID <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
SEX <- c("F", "M", "F", "M", "M", "F", "F", "F", "M", "F")
AGE <- c(50, 40, 28, 50, 27, 23, 56, 47, 20, 38)
AREA <- c("서울", "경기", "제주", "서울", "서울", "서울", "경기", "서울",
          "인천", "경기")
dataframe_ex <- data.frame(ID, SEX, AGE, AREA)
dataframe_ex
```



```{r}
#2 변수,함수

##변수 : 변하는 수
##함수: 특정 기능을 수행하기 위해 사전에 실행된 것


# 변수 속성 확인하기
str(dataframe_ex)

# 숫자와 문자 변수 생성하기
x <- 10
x
y <- "HI"
y
z <- '10'
z

# Hello World 문자 출력하기
print("Hello World")


# 1부터 100까지 더한 값을 출력하기
a <- sum(1:100)
a


# 오늘 날짜 출력하기
Sys.Date()


# 숫자 3개 곱하기
multi_three_return <- function(x, y, z) {
  res <- x*y*z
  return(res)
}
multi_three_return(3, 5, 6)
```



```{r}
#4 조건문과 반복문

#기본 연산

20 %/% 7  #몫
20%%7     #나머지
20 / 7    #나누기 
20 * 7    #곱하기


# 논리 연산자로 진릿값 확인하기
x <- 1:3
y <- 3:1
(x > 0) & (y > 1)
(x > 0) | (y > 1)


# 조건문으로 짝수 홀수 구분하기
a <- 10
if (a %% 2 == 0) {
  print("짝수입니다")
} else {
  print("홀수입니다")
}


# 조건문으로 학점 분류하기
b <- 80
if(b >= 90) {
  print("A 학점입니다")
} else if (b >= 80) {
  print("B 학점입니다")
} else {
  print("c 학점입니다")
}


# for() 함수로 구구단 2단 출력하기
for(i in 1:9) {
  a <- 2*i
  print(a)
}


# for() 함수로 구구단 2단부터 9단까지 출력하기
for(i in 2:9) {
  for(j in 1:9) {
    print(paste(i, " * ", j, " = ", i*j))
  }
}


# apply() 함수로 행렬 값 계산하기
x <- matrix(1:4, 2, 2)
x

#1은 행, 2는 열
apply(x, 1, sum)
apply(x, 2, min)
apply(x, 1, max)


# iris 데이터 세트 구조 확인하기
str(iris)
View(iris)


# apply() 함수로 iris 데이터 세트 값 처리하기
apply(iris[,1:4], 2, sum) # 합
apply(iris[,1:4], 2, mean) # 평균값
apply(iris[,1:4], 2, min) # 최솟값
apply(iris[,1:4], 2, max) # 최댓값
apply(iris[,1:4], 2, median) # 중간값


lapply(iris[, 1:4], sum)


sapply(iris[, 1:4], mean)
```